Add missing Time argument to Resolver_mirage.Make_with_stack
Error was:

    21 | module R = Resolver_mirage.Make_with_stack (Mirage_crypto_rng) (Mclock) (Tcpip_stack_socket)
                                                                         ^^^^^^
    Error: Signature mismatch:
           Modules do not match:
             sig
               val elapsed_ns : unit -> int64
               val period_ns : unit -> int64 option
             end
           is not included in
             Mirage_time.S
           The value `sleep_ns' is required but not provided
           File "src/mirage_time.ml", line 28, characters 2-35:
             Expected declaration